---
- name: Install python-pycurl
  action: apt pkg=$item state=latest
  with_items:
    - python-pycurl

- name: Ensure apt_repo haproxy added
  apt_repository:
    repo: 'ppa:vbernat/haproxy-{{ haproxy_major_version }}'

- name: Install HAProxy
  action: apt pkg=$item state=latest
  with_items:
    - haproxy

- name: Copy HAProxy configuration in place.
  template:
      src: haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg
      backup: yes
      validate: haproxy -f %s -c
  notify: restart haproxy

- name: Ensure HAProxy is started and enabled on boot.
  service: name=haproxy state=started enabled=yes