---
- name: Install python-pycurl
  action: apt pkg={{ item }} state=latest
  with_items:
    - python-pycurl
    - python-pip

- name: Install dependent python modules
  pip:
    name: python-consul
    state: present

- name: Ensure apt_repo haproxy added
  apt_repository:
    repo: 'ppa:vbernat/haproxy-{{ haproxy_major_version }}'

- name: Install HAProxy
  action: apt pkg= {{ item }} state=latest
  with_items:
    - haproxy

- name: Put haproxy-key for SSL
  copy: src=files/haproxy.pem dest=/etc/ssl/certs/haproxy.pem owner=root group=root mode=0644

- name: Copy HAProxy configuration in place.
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    backup: yes
    validate: haproxy -f %s -c
  notify: restart haproxy

- name: Ensure HAProxy is started and enabled on boot.
  service: name=haproxy state=started enabled=yes

- name: Put rsyslogd config file in /etc/rsyslog.d/
  copy: src=files/49-haproxy.conf dest=/etc/rsyslog.d/49-haproxy.conf owner=root group=root mode=0644
  notify: restart rsyslog

- name: Ensure rsyslog is started and enabled on boot.
  service: name=rsyslog state=started enabled=yes

- name: register HAProxy service to Consul with curl check
  consul:
    service_name: haproxy
    service_port: 8080
    http: http://localhost:8080
    interval: 60s

- name: register Keepalived service to Consul
  consul:
    service_name: keepalived
    service_port: 80
    interval: 60s

- name: register Keepalived service to Consul
  consul:
    service_name: rsyslog
    service_port: 80
    interval: 60s